// Hardcoded climate normals for all destinations by month (1-12)
// Data sourced from climate-data.org / weatherspark.com averages
// This is more reliable than API calls since climate normals rarely change

export interface ClimateData {
  avgTempC: number
  avgTempF: number
  rainyDays: number
  humidity: number
  description: string
  packingTip: string
}

interface MonthlyClimate {
  tempC: number
  rainyDays: number
  humidity: number
  desc: string
  tip: string
}

// Helper to build ClimateData from compact format
function toClimate(m: MonthlyClimate): ClimateData {
  return {
    avgTempC: m.tempC,
    avgTempF: Math.round(m.tempC * 9 / 5 + 32),
    rainyDays: m.rainyDays,
    humidity: m.humidity,
    description: m.desc,
    packingTip: m.tip,
  }
}

// Compact monthly data: [tempC, rainyDays, humidity, description, packingTip]
// Indexed by month 0-11 (Jan=0, Dec=11)
type CompactMonth = [number, number, number, string, string]

function fromCompact(data: CompactMonth[]): MonthlyClimate[] {
  return data.map(([tempC, rainyDays, humidity, desc, tip]) => ({
    tempC, rainyDays, humidity, desc, tip,
  }))
}

// ---- Climate data keyed by IATA code ----
const climateDb: Record<string, CompactMonth[]> = {
  // ========== SOUTHEAST ASIA ==========
  BKK: [
    [27, 1, 65, 'Warm & dry, cool season', 'Light clothing, sunscreen'],
    [29, 1, 68, 'Hot & dry', 'Light clothing, sun hat'],
    [30, 2, 68, 'Hot & dry, warming up', 'Light breathable fabrics, sunscreen'],
    [31, 4, 70, 'Very hot, pre-monsoon', 'Lightweight clothing, stay hydrated'],
    [30, 13, 74, 'Hot & humid, rains begin', 'Light rain jacket, breathable clothes'],
    [30, 12, 73, 'Hot & rainy season', 'Rain gear, quick-dry clothing'],
    [29, 14, 74, 'Rainy season, warm', 'Umbrella, waterproof bag'],
    [29, 15, 75, 'Peak rainy season', 'Rain gear, waterproof shoes'],
    [28, 17, 78, 'Rainy & humid', 'Waterproof everything, light layers'],
    [28, 14, 76, 'Late rainy season', 'Rain jacket, breathable fabrics'],
    [28, 5, 68, 'Cooling down, drier', 'Light layers for evening'],
    [27, 1, 64, 'Cool & dry, best weather', 'Light clothing, light jacket for evening'],
  ],
  CNX: [
    [22, 1, 62, 'Cool & dry, best season', 'Light layers, jacket for evenings'],
    [25, 1, 55, 'Warm & dry, hazy', 'Sunscreen, light clothing'],
    [28, 3, 55, 'Hot & dry, burning season haze', 'Face mask for haze, light clothes'],
    [30, 6, 60, 'Very hot, pre-monsoon', 'Light breathable fabrics, sun hat'],
    [28, 14, 72, 'Hot & humid, rains start', 'Rain jacket, light clothing'],
    [27, 14, 75, 'Rainy season', 'Rain gear, quick-dry clothes'],
    [27, 17, 78, 'Peak rainy season', 'Waterproof gear, umbrella'],
    [26, 19, 80, 'Wettest month', 'Full rain gear, waterproof bag'],
    [26, 16, 80, 'Rainy & lush', 'Rain jacket, mosquito repellent'],
    [26, 10, 76, 'Late rains, cooling', 'Light rain jacket, layers'],
    [24, 4, 68, 'Cool & pleasant', 'Light layers, jacket for evening'],
    [22, 1, 64, 'Cool & dry', 'Jacket for morning/evening, layers'],
  ],
  HKT: [
    [27, 4, 72, 'Warm & mostly dry', 'Light beach clothing, sunscreen'],
    [28, 3, 72, 'Hot & dry, peak season', 'Beach wear, sun protection'],
    [29, 4, 73, 'Hot & dry', 'Light breathable clothing'],
    [29, 10, 76, 'Hot, rains increasing', 'Light rain jacket, sunscreen'],
    [28, 18, 80, 'Rainy season starts', 'Rain gear, waterproof bag'],
    [28, 16, 79, 'Rainy season', 'Umbrella, quick-dry clothing'],
    [28, 17, 79, 'Rainy season', 'Rain gear, water shoes'],
    [28, 17, 79, 'Rainy season', 'Waterproof gear, light clothes'],
    [27, 20, 82, 'Wettest month', 'Full rain gear, waterproof everything'],
    [27, 19, 82, 'Very rainy', 'Waterproof bag, rain jacket'],
    [27, 14, 78, 'Late rains', 'Light rain jacket, beach wear'],
    [27, 7, 73, 'Drying out, pleasant', 'Beach clothing, light layers'],
  ],
  DPS: [
    [27, 15, 82, 'Wet season, warm', 'Rain gear, light breathable clothes'],
    [27, 14, 82, 'Wet season', 'Umbrella, quick-dry clothing'],
    [27, 13, 80, 'Late wet season', 'Rain jacket, sunscreen'],
    [27, 8, 78, 'Transition, drying out', 'Light layers, rain jacket'],
    [27, 5, 76, 'Dry season begins', 'Light clothing, sunscreen'],
    [26, 4, 74, 'Dry season, coolest', 'Light layers for evening, sunscreen'],
    [26, 3, 73, 'Dry & cool, peak season', 'Light clothing, sun hat'],
    [26, 2, 72, 'Dry season, best weather', 'Beach wear, sunscreen'],
    [27, 3, 73, 'Dry, warming up', 'Light clothing, sunscreen'],
    [27, 7, 76, 'Transition to wet', 'Light rain jacket, sunscreen'],
    [27, 11, 79, 'Wet season starting', 'Rain gear, breathable clothes'],
    [27, 14, 81, 'Wet season', 'Rain gear, waterproof bag'],
  ],
  SIN: [
    [27, 14, 84, 'Warm & rainy, NE monsoon', 'Umbrella, light breathable clothes'],
    [27, 11, 82, 'Warm, lighter rain', 'Light clothing, rain jacket'],
    [28, 14, 83, 'Hot & humid', 'Light breathable fabrics, umbrella'],
    [28, 15, 84, 'Hot & humid', 'Light clothing, stay hydrated'],
    [28, 14, 83, 'Hot & humid', 'Light breathable clothes, umbrella'],
    [28, 12, 82, 'Hot, drier period', 'Light clothing, sunscreen'],
    [28, 12, 82, 'Hot, SW monsoon', 'Light clothing, sunscreen'],
    [28, 13, 82, 'Hot & humid', 'Light breathable fabrics'],
    [27, 13, 83, 'Hot & humid', 'Umbrella, light clothing'],
    [27, 16, 84, 'Rainy season', 'Rain gear, light clothes'],
    [27, 18, 85, 'Wettest month', 'Umbrella, waterproof bag'],
    [27, 17, 85, 'Rainy season', 'Rain gear, light breathable clothes'],
  ],
  KUL: [
    [28, 12, 80, 'Warm & humid', 'Light breathable clothes, umbrella'],
    [28, 10, 79, 'Warm, lighter rain', 'Light clothing, sunscreen'],
    [28, 13, 80, 'Hot & humid', 'Light breathable fabrics'],
    [28, 15, 82, 'Hot & rainy', 'Rain gear, light clothes'],
    [28, 13, 81, 'Hot & humid', 'Umbrella, breathable clothing'],
    [28, 10, 80, 'Hot, drier', 'Light clothing, sunscreen'],
    [28, 10, 79, 'Hot, less rain', 'Light clothing, sun protection'],
    [28, 12, 80, 'Hot & humid', 'Light breathable fabrics'],
    [27, 14, 82, 'Rainy period', 'Rain jacket, umbrella'],
    [27, 17, 83, 'Rainy season', 'Waterproof gear, light clothes'],
    [27, 18, 84, 'Very rainy', 'Full rain gear, waterproof bag'],
    [27, 16, 82, 'Rainy, year-end', 'Umbrella, light rain jacket'],
  ],
  HAN: [
    [17, 8, 78, 'Cool & drizzly', 'Warm layers, rain jacket'],
    [18, 10, 82, 'Cool & damp', 'Layers, waterproof jacket'],
    [20, 12, 85, 'Warming, humid', 'Light layers, rain jacket'],
    [24, 10, 84, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [28, 11, 78, 'Hot & humid', 'Light breathable clothes, sunscreen'],
    [30, 10, 76, 'Very hot', 'Light clothing, sun hat, stay hydrated'],
    [30, 12, 78, 'Hot & rainy', 'Rain gear, light clothes'],
    [29, 14, 80, 'Hot & very rainy', 'Waterproof gear, umbrella'],
    [28, 10, 78, 'Warm, rains easing', 'Light rain jacket, breathable clothes'],
    [25, 7, 76, 'Cooling, pleasant', 'Light layers, sunscreen'],
    [22, 5, 74, 'Cool & pleasant', 'Light jacket, layers'],
    [18, 6, 76, 'Cool & dry', 'Warm layers, jacket'],
  ],
  SGN: [
    [27, 2, 68, 'Warm & dry', 'Light clothing, sunscreen'],
    [28, 1, 66, 'Hot & dry', 'Light clothing, sun hat'],
    [29, 2, 66, 'Very hot & dry', 'Light breathable fabrics, sunscreen'],
    [30, 5, 70, 'Hottest, rains start', 'Light clothes, rain jacket'],
    [29, 16, 78, 'Rainy season', 'Rain gear, quick-dry clothes'],
    [28, 18, 80, 'Rainy season', 'Umbrella, waterproof bag'],
    [28, 19, 80, 'Rainy season', 'Full rain gear'],
    [28, 19, 80, 'Rainy season', 'Waterproof everything'],
    [27, 20, 82, 'Wettest month', 'Rain gear, waterproof shoes'],
    [27, 18, 80, 'Late rainy season', 'Rain jacket, light clothes'],
    [27, 10, 76, 'Rains easing', 'Light rain jacket, breathable fabrics'],
    [27, 4, 70, 'Dry & pleasant', 'Light clothing, sunscreen'],
  ],
  MNL: [
    [27, 4, 72, 'Warm & dry', 'Light clothing, sunscreen'],
    [27, 3, 70, 'Hot & dry', 'Light clothing, sun protection'],
    [28, 3, 68, 'Hot & dry', 'Sunscreen, light breathable fabrics'],
    [30, 3, 66, 'Hottest month', 'Stay hydrated, light clothing'],
    [30, 8, 72, 'Hot, rains start', 'Rain jacket, light clothes'],
    [29, 14, 78, 'Rainy season', 'Rain gear, waterproof bag'],
    [28, 20, 80, 'Typhoon season', 'Rain gear, check weather alerts'],
    [28, 22, 82, 'Peak typhoon season', 'Waterproof everything, monitor storms'],
    [28, 19, 82, 'Rainy & humid', 'Rain gear, quick-dry clothes'],
    [28, 15, 78, 'Late rainy season', 'Rain jacket, light layers'],
    [28, 10, 76, 'Drying out', 'Light layers, rain jacket'],
    [27, 6, 74, 'Cool & drier', 'Light clothing, light jacket'],
  ],
  PNH: [
    [27, 1, 65, 'Warm & dry', 'Light clothing, sunscreen'],
    [28, 1, 62, 'Hot & dry', 'Light clothes, sun hat'],
    [30, 3, 64, 'Very hot', 'Stay hydrated, light fabrics'],
    [31, 5, 68, 'Hottest month', 'Light clothing, stay cool'],
    [30, 12, 74, 'Hot, rains begin', 'Rain jacket, light clothes'],
    [29, 14, 78, 'Rainy season', 'Rain gear, breathable fabrics'],
    [29, 16, 79, 'Rainy season', 'Umbrella, quick-dry clothes'],
    [28, 17, 80, 'Rainy season', 'Waterproof gear'],
    [28, 19, 82, 'Wettest month', 'Full rain gear, waterproof bag'],
    [28, 17, 80, 'Late rains', 'Rain jacket, light clothes'],
    [28, 7, 72, 'Cooling, drier', 'Light layers'],
    [27, 2, 67, 'Cool & dry', 'Light clothing, jacket for evening'],
  ],
  REP: [
    [26, 1, 65, 'Cool & dry, peak season', 'Light clothing, sun hat for temples'],
    [28, 1, 62, 'Warm & dry', 'Sunscreen, light clothing'],
    [30, 3, 64, 'Hot & dry', 'Stay hydrated, sun protection'],
    [31, 5, 68, 'Very hot', 'Lightweight clothing, lots of water'],
    [30, 12, 74, 'Rains start, still hot', 'Rain jacket, light clothes'],
    [29, 14, 78, 'Rainy season', 'Rain gear, quick-dry clothes'],
    [29, 16, 79, 'Rainy, lush green', 'Umbrella, waterproof bag'],
    [28, 17, 80, 'Rainy season', 'Waterproof gear'],
    [28, 19, 82, 'Wettest month', 'Full rain gear'],
    [28, 17, 80, 'Late rains', 'Rain jacket, light layers'],
    [27, 7, 72, 'Drying, pleasant', 'Light layers for temple visits'],
    [26, 2, 67, 'Cool & dry, peak season', 'Light clothing, jacket for dawn'],
  ],
  VTE: [
    [22, 1, 65, 'Cool & dry', 'Light layers, jacket for evening'],
    [25, 2, 62, 'Warm & dry', 'Light clothing'],
    [28, 3, 62, 'Hot & dry', 'Sunscreen, light fabrics'],
    [30, 6, 68, 'Very hot', 'Stay hydrated, light clothes'],
    [29, 14, 76, 'Rainy season starts', 'Rain gear, light clothing'],
    [28, 15, 78, 'Rainy season', 'Umbrella, waterproof bag'],
    [28, 18, 80, 'Rainy season', 'Full rain gear'],
    [28, 20, 82, 'Wettest month', 'Waterproof everything'],
    [28, 16, 80, 'Rainy, humid', 'Rain jacket, quick-dry clothes'],
    [27, 8, 74, 'Rains easing', 'Light rain jacket'],
    [25, 2, 68, 'Cool & pleasant', 'Light layers'],
    [22, 1, 66, 'Cool & dry', 'Warm layers for evening'],
  ],

  // ========== EAST ASIA ==========
  NRT: [
    [5, 5, 55, 'Cold & dry', 'Warm coat, layers, gloves'],
    [6, 6, 56, 'Cold, occasional snow', 'Warm coat, layers'],
    [10, 10, 58, 'Cool, cherry blossom season', 'Light jacket, layers'],
    [15, 10, 62, 'Mild & pleasant', 'Light jacket, comfortable layers'],
    [20, 10, 65, 'Warm & pleasant', 'Light layers, rain jacket'],
    [23, 12, 72, 'Rainy season (tsuyu)', 'Rain gear, umbrella essential'],
    [27, 10, 75, 'Hot & humid', 'Light breathable clothes, umbrella'],
    [28, 8, 72, 'Very hot & humid', 'Light clothing, stay hydrated'],
    [25, 11, 72, 'Warm, typhoon season', 'Rain jacket, check forecasts'],
    [19, 10, 68, 'Cool & pleasant, autumn colors', 'Light jacket, layers'],
    [14, 7, 62, 'Cool & crisp', 'Warm jacket, layers'],
    [8, 5, 56, 'Cold & dry', 'Warm coat, scarf, gloves'],
  ],
  KIX: [
    [5, 5, 60, 'Cold & dry', 'Warm coat, layers'],
    [6, 6, 58, 'Cold, some rain', 'Warm coat, umbrella'],
    [10, 9, 58, 'Cool, cherry blossoms', 'Light jacket, layers'],
    [16, 10, 60, 'Mild & pleasant', 'Light layers'],
    [20, 10, 62, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [24, 12, 70, 'Rainy season', 'Rain gear, umbrella'],
    [28, 10, 74, 'Hot & humid', 'Light breathable clothes'],
    [29, 7, 70, 'Very hot', 'Light clothing, stay hydrated'],
    [25, 10, 70, 'Warm, typhoons possible', 'Rain jacket, layers'],
    [19, 8, 66, 'Cool & pleasant', 'Light jacket, layers'],
    [14, 6, 62, 'Cool, autumn leaves', 'Warm jacket'],
    [8, 5, 60, 'Cold', 'Warm coat, layers'],
  ],
  ICN: [
    [-2, 6, 58, 'Very cold & dry', 'Heavy winter coat, thermals, gloves'],
    [1, 5, 56, 'Cold, occasional snow', 'Warm coat, layers'],
    [6, 7, 55, 'Cool, spring starting', 'Warm jacket, layers'],
    [13, 8, 56, 'Mild & pleasant', 'Light jacket, layers'],
    [18, 8, 62, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [23, 10, 68, 'Hot & humid', 'Light breathable clothes, umbrella'],
    [26, 16, 78, 'Rainy season, very humid', 'Rain gear, light clothes'],
    [27, 12, 76, 'Hot & humid', 'Light clothing, stay hydrated'],
    [22, 8, 68, 'Warm, pleasant', 'Light layers, jacket for evening'],
    [15, 6, 62, 'Cool & pleasant, autumn', 'Light jacket, layers'],
    [7, 7, 60, 'Cool to cold', 'Warm jacket, layers'],
    [0, 6, 58, 'Cold & dry', 'Heavy coat, thermals'],
  ],
  HKG: [
    [17, 5, 72, 'Cool & dry', 'Light jacket, layers'],
    [17, 7, 78, 'Cool & humid', 'Light layers, rain jacket'],
    [19, 9, 80, 'Mild, getting humid', 'Light jacket, umbrella'],
    [23, 11, 82, 'Warm & humid', 'Light breathable clothes, rain gear'],
    [27, 14, 82, 'Hot & rainy', 'Rain gear, light clothes'],
    [28, 17, 82, 'Hot, typhoon season starts', 'Umbrella, light clothes, check weather'],
    [29, 14, 80, 'Very hot & humid', 'Light clothing, stay hydrated'],
    [29, 14, 80, 'Very hot, typhoon risk', 'Light clothes, monitor storm alerts'],
    [28, 12, 76, 'Hot, typhoon season', 'Light clothing, rain jacket'],
    [26, 6, 70, 'Warm & pleasant', 'Light layers'],
    [22, 4, 66, 'Cool & pleasant', 'Light jacket'],
    [18, 4, 68, 'Cool & dry', 'Light jacket, layers'],
  ],
  TPE: [
    [16, 12, 76, 'Cool & rainy', 'Warm layers, waterproof jacket'],
    [16, 12, 78, 'Cool & damp', 'Layers, umbrella'],
    [19, 12, 76, 'Cool, warming up', 'Light jacket, umbrella'],
    [22, 12, 76, 'Mild & rainy', 'Rain jacket, light layers'],
    [25, 13, 76, 'Warm & humid', 'Light clothes, rain gear'],
    [28, 13, 76, 'Hot & humid, plum rain', 'Rain gear, light breathable clothes'],
    [30, 9, 72, 'Very hot', 'Light clothing, sunscreen, stay hydrated'],
    [29, 12, 74, 'Hot, typhoon season', 'Light clothes, check weather alerts'],
    [28, 10, 72, 'Warm, typhoons possible', 'Light layers, rain jacket'],
    [24, 8, 72, 'Pleasant & warm', 'Light layers'],
    [21, 9, 74, 'Cool & pleasant', 'Light jacket, layers'],
    [17, 10, 74, 'Cool & damp', 'Warm layers, umbrella'],
  ],
  PEK: [
    [-3, 2, 44, 'Very cold & dry', 'Heavy coat, thermals, scarf'],
    [0, 3, 44, 'Cold & dry', 'Heavy winter coat, layers'],
    [7, 3, 40, 'Cool, windy, dusty', 'Warm jacket, face mask for dust'],
    [15, 4, 42, 'Mild & pleasant', 'Light jacket, layers'],
    [22, 5, 48, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [27, 8, 56, 'Hot & humid', 'Light breathable clothes'],
    [28, 12, 68, 'Hot & rainy', 'Rain gear, light clothes'],
    [27, 10, 70, 'Hot & humid', 'Umbrella, light clothing'],
    [22, 5, 58, 'Warm & pleasant', 'Light layers'],
    [15, 4, 52, 'Cool & pleasant, autumn', 'Light jacket, layers'],
    [6, 3, 48, 'Cold', 'Warm coat, layers'],
    [-1, 2, 44, 'Very cold', 'Heavy coat, thermals, gloves'],
  ],
  PVG: [
    [4, 7, 72, 'Cold & damp', 'Warm coat, layers'],
    [6, 8, 72, 'Cold & damp', 'Warm layers, umbrella'],
    [10, 10, 72, 'Cool, warming up', 'Light jacket, rain gear'],
    [16, 10, 70, 'Mild & pleasant', 'Light layers, umbrella'],
    [21, 10, 70, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [25, 12, 76, 'Hot & rainy (plum rain)', 'Rain gear, light clothes'],
    [30, 10, 74, 'Very hot & humid', 'Light clothing, stay hydrated'],
    [30, 9, 72, 'Very hot', 'Light breathable clothes, sunscreen'],
    [26, 8, 70, 'Warm & pleasant', 'Light layers'],
    [20, 6, 68, 'Cool & pleasant', 'Light jacket'],
    [14, 5, 68, 'Cool', 'Warm jacket, layers'],
    [6, 5, 70, 'Cold & damp', 'Warm coat, layers'],
  ],

  // ========== SOUTH ASIA ==========
  BOM: [
    [25, 0, 62, 'Warm & dry, pleasant', 'Light clothing, sunscreen'],
    [26, 0, 60, 'Warm & dry', 'Light clothing'],
    [28, 0, 62, 'Hot & dry', 'Light breathable fabrics'],
    [30, 0, 66, 'Very hot & humid', 'Light clothes, stay hydrated'],
    [31, 2, 70, 'Hot & humid, pre-monsoon', 'Light clothing, increasing humidity'],
    [29, 18, 82, 'Monsoon starts', 'Full rain gear, waterproof everything'],
    [28, 24, 86, 'Peak monsoon', 'Waterproof shoes, rain gear essential'],
    [27, 22, 86, 'Heavy monsoon', 'Waterproof everything'],
    [28, 14, 82, 'Late monsoon', 'Rain gear, light clothes'],
    [29, 5, 74, 'Post-monsoon', 'Light clothing, occasional rain gear'],
    [28, 2, 66, 'Pleasant & dry', 'Light clothing'],
    [26, 0, 64, 'Cool & pleasant', 'Light layers'],
  ],
  DEL: [
    [14, 2, 62, 'Cool & foggy', 'Warm layers, jacket'],
    [17, 2, 56, 'Cool & pleasant', 'Light layers, jacket for morning'],
    [23, 2, 44, 'Warm & dry', 'Light clothing, sunscreen'],
    [30, 1, 32, 'Very hot & dry', 'Light clothing, sun protection, stay hydrated'],
    [34, 3, 34, 'Extreme heat', 'Light cotton clothes, avoid midday sun'],
    [34, 6, 48, 'Very hot, pre-monsoon', 'Light clothes, hat, stay hydrated'],
    [31, 14, 72, 'Monsoon, humid', 'Rain gear, light breathable clothes'],
    [30, 13, 76, 'Monsoon continues', 'Waterproof gear, umbrella'],
    [29, 6, 68, 'Warm, monsoon ending', 'Light clothes, rain jacket'],
    [26, 2, 56, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [21, 1, 54, 'Cool & pleasant', 'Light layers'],
    [15, 1, 60, 'Cool & foggy', 'Warm layers, jacket'],
  ],
  GOI: [
    [26, 0, 62, 'Warm & dry, peak season', 'Beach wear, light clothing'],
    [27, 0, 62, 'Warm & dry', 'Light clothing, sunscreen'],
    [28, 1, 64, 'Hot & dry', 'Light fabrics, sun protection'],
    [30, 2, 68, 'Very hot', 'Light clothes, stay hydrated'],
    [30, 8, 74, 'Hot, pre-monsoon', 'Light clothes, rain approaching'],
    [28, 22, 84, 'Monsoon starts', 'Full rain gear, waterproof bag'],
    [27, 26, 86, 'Peak monsoon', 'Waterproof everything'],
    [27, 22, 86, 'Heavy rains', 'Rain gear, waterproof shoes'],
    [28, 14, 82, 'Late monsoon', 'Rain jacket, light clothes'],
    [29, 8, 76, 'Rains easing', 'Light clothes, rain jacket'],
    [28, 3, 68, 'Pleasant, drying out', 'Light clothing, beach wear'],
    [27, 1, 64, 'Cool & dry, peak season', 'Beach wear, light layers for evening'],
  ],
  CMB: [
    [27, 7, 74, 'Warm, inter-monsoon', 'Light clothing, rain jacket'],
    [27, 6, 72, 'Warm & drier', 'Light clothing, sunscreen'],
    [28, 8, 74, 'Hot & humid', 'Light breathable fabrics'],
    [28, 14, 78, 'Hot, SW monsoon starts', 'Rain gear, light clothes'],
    [28, 16, 80, 'Rainy season', 'Rain gear, waterproof bag'],
    [27, 12, 78, 'Rainy season', 'Umbrella, quick-dry clothes'],
    [27, 10, 76, 'SW monsoon', 'Rain jacket, light clothes'],
    [27, 10, 76, 'Rainy season', 'Rain gear, light breathable clothes'],
    [27, 12, 78, 'Rainy period', 'Umbrella, waterproof bag'],
    [27, 16, 80, 'NE monsoon starts', 'Full rain gear'],
    [27, 14, 78, 'Rainy season', 'Rain gear, light clothes'],
    [27, 10, 76, 'Drying out', 'Light clothing, rain jacket'],
  ],
  KTM: [
    [10, 2, 72, 'Cool & dry', 'Warm layers, jacket'],
    [13, 3, 68, 'Cool, warming up', 'Warm layers'],
    [17, 4, 60, 'Mild & pleasant', 'Light layers, sunscreen'],
    [21, 6, 56, 'Warm & pleasant', 'Light clothing, layers'],
    [23, 10, 62, 'Warm, pre-monsoon', 'Light clothes, rain jacket'],
    [24, 16, 76, 'Hot, monsoon starts', 'Rain gear, light breathable clothes'],
    [24, 22, 82, 'Peak monsoon', 'Waterproof everything'],
    [24, 20, 84, 'Heavy monsoon', 'Full rain gear, waterproof bag'],
    [23, 12, 80, 'Late monsoon', 'Rain jacket, light layers'],
    [20, 4, 72, 'Cool & pleasant, trekking season', 'Layers, trekking gear'],
    [15, 1, 68, 'Cool & dry, trekking season', 'Warm layers, jacket'],
    [11, 1, 70, 'Cold & dry', 'Warm coat, layers'],
  ],

  // ========== MIDDLE EAST ==========
  DXB: [
    [20, 1, 62, 'Mild & pleasant', 'Light layers, jacket for evening'],
    [21, 1, 60, 'Mild & pleasant', 'Light clothing'],
    [24, 2, 58, 'Warm & dry', 'Light clothing, sunscreen'],
    [28, 1, 50, 'Hot & dry', 'Light clothing, sun protection'],
    [33, 0, 48, 'Very hot', 'Light clothing, stay hydrated'],
    [35, 0, 52, 'Extremely hot', 'Light loose clothing, avoid midday sun'],
    [37, 0, 56, 'Extreme heat', 'Stay indoors midday, light clothing'],
    [37, 0, 58, 'Extreme heat', 'Air-conditioned activities, light clothes'],
    [34, 0, 58, 'Very hot', 'Light clothing, sun protection'],
    [30, 0, 56, 'Hot & dry', 'Light clothing, sunscreen'],
    [25, 1, 58, 'Warm & pleasant', 'Light layers'],
    [21, 1, 62, 'Mild & pleasant', 'Light layers, jacket for evening'],
  ],
  IST: [
    [6, 12, 76, 'Cold & wet', 'Warm coat, waterproof jacket'],
    [6, 10, 74, 'Cold, some rain', 'Warm coat, layers, umbrella'],
    [9, 9, 72, 'Cool, spring starting', 'Warm jacket, layers'],
    [13, 8, 68, 'Mild & pleasant', 'Light jacket, layers'],
    [18, 7, 68, 'Warm & pleasant', 'Light clothing, jacket for evening'],
    [23, 5, 62, 'Hot & dry', 'Light clothing, sunscreen'],
    [25, 3, 58, 'Hot & sunny', 'Light clothing, sun hat, sunscreen'],
    [26, 3, 58, 'Hot & sunny', 'Light clothes, stay hydrated'],
    [22, 4, 62, 'Warm & pleasant', 'Light layers'],
    [17, 8, 70, 'Cool & rainy', 'Light jacket, umbrella'],
    [12, 10, 74, 'Cool & wet', 'Warm jacket, rain gear'],
    [8, 12, 76, 'Cold & wet', 'Warm coat, waterproof jacket'],
  ],
  DOH: [
    [18, 1, 60, 'Cool & pleasant', 'Light layers'],
    [19, 1, 58, 'Cool & pleasant', 'Light clothing'],
    [23, 1, 52, 'Warm & dry', 'Light clothing, sunscreen'],
    [28, 1, 44, 'Hot', 'Light clothing, sun protection'],
    [34, 0, 38, 'Very hot', 'Light clothing, stay indoors midday'],
    [37, 0, 38, 'Extremely hot', 'Avoid outdoor activities, light clothes'],
    [38, 0, 44, 'Extreme heat', 'Stay in air conditioning, loose clothing'],
    [37, 0, 48, 'Extreme heat', 'Air-conditioned venues, light clothes'],
    [34, 0, 50, 'Very hot', 'Light clothing, sun protection'],
    [30, 0, 52, 'Hot', 'Light clothing, sunscreen'],
    [24, 1, 56, 'Warm & pleasant', 'Light layers'],
    [19, 1, 60, 'Cool & pleasant', 'Light layers, jacket for evening'],
  ],
  TLV: [
    [13, 10, 66, 'Cool & rainy', 'Warm layers, waterproof jacket'],
    [14, 8, 64, 'Cool, some rain', 'Layers, umbrella'],
    [16, 5, 62, 'Mild, warming up', 'Light jacket, layers'],
    [19, 2, 58, 'Warm & pleasant', 'Light clothing'],
    [22, 0, 60, 'Hot & dry', 'Light clothing, sunscreen'],
    [25, 0, 62, 'Hot & humid', 'Light breathable clothes'],
    [27, 0, 66, 'Very hot & humid', 'Light clothing, stay hydrated'],
    [28, 0, 68, 'Hot & humid', 'Light clothes, sun protection'],
    [26, 0, 64, 'Hot & dry', 'Light clothing, sunscreen'],
    [23, 3, 60, 'Warm & pleasant', 'Light layers'],
    [19, 5, 58, 'Cool, some rain', 'Light jacket, umbrella'],
    [14, 9, 64, 'Cool & rainy', 'Warm layers, waterproof jacket'],
  ],
  AMM: [
    [8, 10, 70, 'Cool & rainy', 'Warm coat, waterproof jacket'],
    [9, 9, 66, 'Cool, some rain', 'Warm layers, umbrella'],
    [13, 6, 56, 'Mild, warming up', 'Light jacket, layers'],
    [17, 3, 46, 'Warm & pleasant', 'Light clothing, layers'],
    [22, 1, 36, 'Hot & dry', 'Light clothing, sunscreen'],
    [25, 0, 34, 'Very hot & dry', 'Light clothing, stay hydrated'],
    [27, 0, 36, 'Very hot', 'Light clothes, sun hat'],
    [28, 0, 38, 'Hottest month', 'Light loose clothing, stay hydrated'],
    [26, 0, 40, 'Hot & dry', 'Light clothing, sunscreen'],
    [22, 2, 46, 'Warm & pleasant', 'Light layers'],
    [15, 5, 58, 'Cool, rains return', 'Warm jacket, umbrella'],
    [9, 8, 68, 'Cool & rainy', 'Warm coat, rain gear'],
  ],
  CAI: [
    [14, 2, 56, 'Cool & dry', 'Warm layers, jacket'],
    [15, 1, 50, 'Cool & dry', 'Light jacket, layers'],
    [18, 1, 44, 'Mild & pleasant', 'Light clothing, sunscreen'],
    [23, 1, 36, 'Warm & dry', 'Light clothing, sun hat'],
    [27, 0, 34, 'Hot & dry', 'Light clothing, sunscreen, stay hydrated'],
    [30, 0, 34, 'Very hot', 'Light clothing, avoid midday sun'],
    [31, 0, 38, 'Very hot', 'Light loose clothing, stay hydrated'],
    [31, 0, 40, 'Very hot', 'Light clothes, sun protection'],
    [29, 0, 42, 'Hot & dry', 'Light clothing, sunscreen'],
    [25, 1, 48, 'Warm & pleasant', 'Light clothing, layers'],
    [20, 1, 54, 'Mild & pleasant', 'Light jacket, layers'],
    [15, 2, 58, 'Cool & dry', 'Warm layers, jacket'],
  ],

  // ========== EUROPE ==========
  LHR: [
    [5, 11, 80, 'Cold & damp', 'Warm coat, waterproof jacket, layers'],
    [5, 8, 76, 'Cold & damp', 'Warm coat, layers'],
    [8, 9, 72, 'Cool, spring starting', 'Warm jacket, layers'],
    [11, 8, 66, 'Mild & pleasant', 'Light jacket, layers'],
    [14, 8, 64, 'Warm & pleasant', 'Light layers, rain jacket'],
    [18, 7, 64, 'Warm & pleasant', 'Light clothing, light jacket'],
    [20, 7, 64, 'Warm, occasional rain', 'Light layers, rain jacket'],
    [20, 7, 66, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [17, 7, 70, 'Mild, cooling down', 'Light jacket, layers'],
    [13, 9, 76, 'Cool & rainy', 'Warm jacket, waterproof coat'],
    [9, 10, 80, 'Cold & damp', 'Warm coat, umbrella'],
    [6, 10, 82, 'Cold & damp', 'Warm coat, waterproof layers'],
  ],
  CDG: [
    [4, 10, 82, 'Cold & damp', 'Warm coat, layers, umbrella'],
    [5, 8, 78, 'Cold, some rain', 'Warm coat, layers'],
    [9, 9, 72, 'Cool, spring starting', 'Warm jacket, layers'],
    [12, 8, 66, 'Mild & pleasant', 'Light jacket, layers'],
    [16, 9, 64, 'Warm & pleasant', 'Light layers, rain jacket'],
    [19, 8, 62, 'Warm & pleasant', 'Light clothing, light jacket'],
    [22, 7, 60, 'Warm & sunny', 'Light clothing, sunscreen'],
    [22, 7, 60, 'Warm & pleasant', 'Light clothing, sun hat'],
    [18, 7, 66, 'Mild, cooling down', 'Light jacket, layers'],
    [13, 9, 74, 'Cool & rainy', 'Warm jacket, umbrella'],
    [8, 10, 80, 'Cold & damp', 'Warm coat, rain gear'],
    [5, 10, 82, 'Cold & damp', 'Warm coat, layers'],
  ],
  AMS: [
    [3, 13, 86, 'Cold & damp', 'Warm coat, waterproof jacket'],
    [4, 10, 82, 'Cold & damp', 'Warm coat, layers, umbrella'],
    [7, 10, 78, 'Cool, spring starting', 'Warm jacket, layers'],
    [10, 9, 72, 'Mild, tulip season', 'Light jacket, layers'],
    [14, 9, 70, 'Warm & pleasant', 'Light layers, rain jacket'],
    [17, 8, 70, 'Warm & pleasant', 'Light clothing, light jacket'],
    [19, 9, 72, 'Warm, some rain', 'Light layers, rain jacket'],
    [19, 9, 72, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [16, 9, 76, 'Mild, cooling down', 'Light jacket, layers'],
    [12, 11, 80, 'Cool & rainy', 'Warm jacket, waterproof coat'],
    [7, 12, 84, 'Cold & wet', 'Warm coat, rain gear'],
    [4, 12, 86, 'Cold & damp', 'Warm coat, waterproof layers'],
  ],
  BCN: [
    [10, 4, 68, 'Cool & mild', 'Warm jacket, layers'],
    [11, 4, 66, 'Cool & mild', 'Warm jacket, layers'],
    [13, 5, 64, 'Mild, spring starting', 'Light jacket, layers'],
    [16, 7, 64, 'Mild & pleasant', 'Light layers'],
    [19, 6, 66, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [23, 4, 64, 'Hot & sunny', 'Light clothing, sun hat'],
    [26, 3, 64, 'Hot & sunny', 'Beach wear, sunscreen'],
    [26, 5, 68, 'Hot & humid', 'Light clothing, beach essentials'],
    [23, 7, 70, 'Warm, some rain', 'Light layers, rain jacket'],
    [19, 8, 72, 'Mild & rainy', 'Light jacket, umbrella'],
    [14, 5, 70, 'Cool & mild', 'Warm jacket, layers'],
    [10, 5, 68, 'Cool', 'Warm jacket, layers'],
  ],
  LIS: [
    [12, 8, 76, 'Cool & rainy', 'Warm layers, waterproof jacket'],
    [13, 7, 72, 'Cool, some rain', 'Warm jacket, umbrella'],
    [15, 6, 68, 'Mild & pleasant', 'Light jacket, layers'],
    [17, 7, 64, 'Mild & pleasant', 'Light layers'],
    [19, 5, 62, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [22, 2, 56, 'Hot & dry', 'Light clothing, sun hat'],
    [25, 1, 52, 'Hot & sunny', 'Light clothes, sunscreen, stay hydrated'],
    [25, 1, 52, 'Hot & sunny', 'Beach essentials, sun protection'],
    [23, 3, 58, 'Warm & pleasant', 'Light layers'],
    [19, 7, 68, 'Mild, some rain', 'Light jacket, umbrella'],
    [15, 8, 74, 'Cool & rainy', 'Warm jacket, rain gear'],
    [12, 9, 78, 'Cool & rainy', 'Warm layers, waterproof jacket'],
  ],
  PRG: [
    [-1, 6, 80, 'Cold & grey', 'Heavy coat, thermals, hat'],
    [1, 5, 76, 'Cold, some snow', 'Warm coat, layers'],
    [5, 5, 68, 'Cool, spring starting', 'Warm jacket, layers'],
    [10, 6, 62, 'Mild & pleasant', 'Light jacket, layers'],
    [15, 8, 64, 'Warm & pleasant', 'Light layers, rain jacket'],
    [19, 8, 64, 'Warm & pleasant', 'Light clothing, light jacket'],
    [21, 8, 64, 'Warm, occasional storms', 'Light clothing, rain jacket'],
    [20, 7, 64, 'Warm & pleasant', 'Light clothing, light layers'],
    [16, 5, 66, 'Mild, cooling down', 'Light jacket, layers'],
    [10, 5, 72, 'Cool & pleasant', 'Warm jacket, layers'],
    [4, 5, 80, 'Cold & grey', 'Warm coat, layers'],
    [0, 5, 82, 'Cold, possible snow', 'Heavy coat, warm layers'],
  ],
  BUD: [
    [0, 5, 76, 'Cold, possible snow', 'Heavy coat, thermals, hat'],
    [3, 5, 72, 'Cold, some snow', 'Warm coat, layers'],
    [8, 5, 64, 'Cool, spring starting', 'Warm jacket, layers'],
    [13, 6, 58, 'Mild & pleasant', 'Light jacket, layers'],
    [18, 8, 60, 'Warm & pleasant', 'Light layers, rain jacket'],
    [22, 8, 58, 'Warm & sunny', 'Light clothing, sunscreen'],
    [24, 6, 56, 'Hot & sunny', 'Light clothes, sun hat'],
    [24, 5, 56, 'Hot & sunny', 'Light clothing, sunscreen'],
    [19, 5, 60, 'Warm, cooling down', 'Light jacket, layers'],
    [13, 5, 68, 'Cool & pleasant', 'Warm jacket, layers'],
    [6, 6, 76, 'Cold & grey', 'Warm coat, layers'],
    [1, 5, 78, 'Cold, possible snow', 'Heavy coat, warm layers'],
  ],
  ATH: [
    [10, 8, 68, 'Cool & rainy', 'Warm jacket, waterproof layer'],
    [11, 7, 66, 'Cool, some rain', 'Warm jacket, layers'],
    [13, 6, 62, 'Mild, warming up', 'Light jacket, layers'],
    [17, 4, 56, 'Warm & pleasant', 'Light layers, sunscreen'],
    [22, 3, 50, 'Hot & dry', 'Light clothing, sunscreen'],
    [27, 1, 42, 'Very hot & dry', 'Light clothing, sun hat, stay hydrated'],
    [30, 0, 38, 'Very hot & dry', 'Light clothes, hat, water bottle'],
    [30, 0, 38, 'Very hot & dry', 'Light clothing, stay hydrated'],
    [26, 2, 46, 'Hot & dry', 'Light clothing, sunscreen'],
    [20, 5, 58, 'Warm & pleasant', 'Light layers'],
    [15, 7, 66, 'Mild, some rain', 'Warm jacket, umbrella'],
    [11, 9, 70, 'Cool & rainy', 'Warm jacket, rain gear'],
  ],
  FCO: [
    [8, 7, 72, 'Cool & rainy', 'Warm coat, waterproof jacket'],
    [9, 7, 70, 'Cool, some rain', 'Warm jacket, umbrella'],
    [12, 6, 66, 'Mild, warming up', 'Light jacket, layers'],
    [15, 6, 62, 'Mild & pleasant', 'Light layers'],
    [19, 4, 58, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [24, 2, 52, 'Hot & sunny', 'Light clothing, sun hat'],
    [27, 1, 46, 'Very hot', 'Light clothes, sunscreen, stay hydrated'],
    [27, 2, 48, 'Very hot', 'Light clothing, water bottle'],
    [23, 4, 56, 'Warm & pleasant', 'Light layers'],
    [18, 7, 66, 'Mild, some rain', 'Light jacket, umbrella'],
    [13, 8, 72, 'Cool & rainy', 'Warm jacket, rain gear'],
    [9, 8, 74, 'Cool & rainy', 'Warm coat, waterproof layers'],
  ],
  BER: [
    [0, 7, 82, 'Cold & grey', 'Heavy coat, thermals, hat'],
    [1, 5, 78, 'Cold, some snow', 'Warm coat, layers'],
    [5, 6, 70, 'Cool, spring starting', 'Warm jacket, layers'],
    [10, 5, 62, 'Mild & pleasant', 'Light jacket, layers'],
    [15, 7, 62, 'Warm & pleasant', 'Light layers, rain jacket'],
    [19, 7, 64, 'Warm & pleasant', 'Light clothing, light jacket'],
    [21, 8, 64, 'Warm, occasional storms', 'Light clothing, rain jacket'],
    [21, 7, 64, 'Warm & pleasant', 'Light clothing, layers'],
    [16, 6, 68, 'Mild, cooling down', 'Light jacket, layers'],
    [10, 5, 76, 'Cool & pleasant', 'Warm jacket, layers'],
    [5, 6, 82, 'Cold & grey', 'Warm coat, layers'],
    [1, 7, 84, 'Cold, possible snow', 'Heavy coat, warm layers'],
  ],
  VIE: [
    [0, 6, 76, 'Cold, possible snow', 'Heavy coat, thermals'],
    [2, 5, 72, 'Cold, some snow', 'Warm coat, layers'],
    [7, 6, 64, 'Cool, spring starting', 'Warm jacket, layers'],
    [12, 6, 58, 'Mild & pleasant', 'Light jacket, layers'],
    [17, 8, 60, 'Warm & pleasant', 'Light layers, rain jacket'],
    [21, 8, 60, 'Warm & pleasant', 'Light clothing, light jacket'],
    [23, 7, 58, 'Warm & sunny', 'Light clothing, sunscreen'],
    [23, 6, 58, 'Warm & pleasant', 'Light clothing, light layers'],
    [18, 5, 62, 'Mild, cooling down', 'Light jacket, layers'],
    [12, 5, 70, 'Cool & pleasant', 'Warm jacket, layers'],
    [6, 6, 78, 'Cold & grey', 'Warm coat, layers'],
    [1, 6, 78, 'Cold, possible snow', 'Heavy coat, warm layers'],
  ],
  WAW: [
    [-2, 7, 82, 'Very cold, snow', 'Heavy coat, thermals, hat, gloves'],
    [-1, 5, 78, 'Cold, some snow', 'Warm coat, layers'],
    [4, 5, 70, 'Cool, spring starting', 'Warm jacket, layers'],
    [10, 6, 62, 'Mild & pleasant', 'Light jacket, layers'],
    [15, 7, 62, 'Warm & pleasant', 'Light layers, rain jacket'],
    [19, 8, 64, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [21, 8, 64, 'Warm, occasional storms', 'Light clothing, umbrella'],
    [20, 6, 64, 'Warm & pleasant', 'Light clothing, light layers'],
    [15, 5, 68, 'Mild, cooling down', 'Light jacket, layers'],
    [9, 5, 76, 'Cool & pleasant', 'Warm jacket, layers'],
    [4, 6, 82, 'Cold & grey', 'Warm coat, layers'],
    [0, 7, 84, 'Very cold, possible snow', 'Heavy coat, warm layers'],
  ],
  KRK: [
    [-2, 7, 80, 'Very cold, snow', 'Heavy coat, thermals, hat'],
    [0, 5, 76, 'Cold, some snow', 'Warm coat, layers'],
    [5, 5, 68, 'Cool, spring starting', 'Warm jacket, layers'],
    [10, 7, 62, 'Mild & pleasant', 'Light jacket, layers'],
    [15, 9, 64, 'Warm & pleasant', 'Light layers, rain jacket'],
    [19, 10, 66, 'Warm, some rain', 'Light clothing, umbrella'],
    [21, 10, 66, 'Warm, occasional storms', 'Light clothing, rain jacket'],
    [20, 8, 66, 'Warm & pleasant', 'Light clothing, layers'],
    [15, 6, 70, 'Mild, cooling down', 'Light jacket, layers'],
    [10, 5, 76, 'Cool & pleasant', 'Warm jacket, layers'],
    [4, 6, 80, 'Cold & grey', 'Warm coat, layers'],
    [-1, 6, 82, 'Very cold, possible snow', 'Heavy coat, warm layers'],
  ],
  CPH: [
    [1, 10, 84, 'Cold & dark', 'Heavy coat, thermals, hat'],
    [1, 7, 82, 'Cold, some snow', 'Warm coat, layers'],
    [3, 7, 78, 'Cool, spring starting', 'Warm jacket, layers'],
    [8, 6, 70, 'Cool & pleasant', 'Warm jacket, light layers'],
    [13, 7, 66, 'Mild & pleasant', 'Light jacket, layers'],
    [17, 7, 66, 'Warm & pleasant', 'Light clothing, light jacket'],
    [19, 9, 70, 'Warm, some rain', 'Light layers, rain jacket'],
    [19, 9, 72, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [15, 8, 76, 'Mild, cooling down', 'Light jacket, layers'],
    [10, 9, 80, 'Cool & rainy', 'Warm jacket, waterproof coat'],
    [5, 10, 84, 'Cold & dark', 'Warm coat, rain gear'],
    [2, 10, 86, 'Cold & dark', 'Heavy coat, warm layers'],
  ],
  DUB: [
    [5, 13, 84, 'Cold & wet', 'Warm coat, waterproof jacket'],
    [5, 10, 80, 'Cold & damp', 'Warm coat, layers, umbrella'],
    [7, 10, 78, 'Cool, spring starting', 'Warm jacket, rain gear'],
    [9, 9, 72, 'Cool & mild', 'Warm jacket, layers'],
    [12, 9, 70, 'Mild & pleasant', 'Light layers, rain jacket'],
    [15, 8, 70, 'Warm & pleasant', 'Light clothing, light jacket'],
    [17, 9, 72, 'Warm, occasional rain', 'Light layers, rain jacket'],
    [17, 10, 74, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [14, 9, 76, 'Mild, cooling down', 'Light jacket, layers, umbrella'],
    [11, 11, 80, 'Cool & rainy', 'Warm jacket, waterproof coat'],
    [7, 11, 82, 'Cold & wet', 'Warm coat, rain gear'],
    [5, 12, 84, 'Cold & wet', 'Warm coat, waterproof layers'],
  ],

  // ========== AMERICAS ==========
  JFK: [
    [-1, 8, 62, 'Very cold, snow', 'Heavy coat, thermals, boots'],
    [0, 7, 60, 'Cold, some snow', 'Warm coat, layers'],
    [5, 9, 58, 'Cool, spring starting', 'Warm jacket, layers'],
    [12, 9, 56, 'Mild & pleasant', 'Light jacket, layers'],
    [18, 9, 60, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [23, 8, 64, 'Hot & humid', 'Light breathable clothes'],
    [26, 8, 64, 'Hot & humid', 'Light clothing, stay hydrated'],
    [26, 8, 66, 'Hot & humid', 'Light clothing, sunscreen'],
    [21, 7, 64, 'Warm, pleasant', 'Light layers'],
    [15, 7, 62, 'Cool & pleasant, fall foliage', 'Light jacket, layers'],
    [9, 8, 64, 'Cool to cold', 'Warm coat, layers'],
    [2, 8, 64, 'Cold, possible snow', 'Heavy coat, warm layers'],
  ],
  LAX: [
    [14, 4, 62, 'Mild & pleasant', 'Light layers, light jacket'],
    [14, 4, 64, 'Mild, some rain', 'Light layers, rain jacket'],
    [15, 4, 64, 'Mild & pleasant', 'Light layers'],
    [16, 2, 64, 'Mild & dry', 'Light clothing, layers'],
    [17, 1, 68, 'Warm, June gloom fog', 'Light layers, light jacket for fog'],
    [19, 0, 70, 'Warm, coastal fog', 'Light clothing, light jacket'],
    [22, 0, 68, 'Warm & dry', 'Light clothing, sunscreen'],
    [22, 0, 68, 'Warm & dry', 'Light clothing, beach essentials'],
    [22, 1, 66, 'Warm & dry', 'Light clothing, sunscreen'],
    [19, 2, 66, 'Warm & pleasant', 'Light layers'],
    [16, 3, 58, 'Mild & dry', 'Light layers, light jacket'],
    [14, 4, 60, 'Mild, some rain', 'Light layers, rain jacket'],
  ],
  MIA: [
    [21, 6, 72, 'Warm & pleasant', 'Light clothing, light layers for AC'],
    [22, 5, 70, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [23, 5, 68, 'Warm & pleasant', 'Light clothing, sunscreen'],
    [25, 5, 66, 'Hot & pleasant', 'Light clothing, sun protection'],
    [27, 10, 72, 'Hot & humid, rains start', 'Light clothes, rain jacket'],
    [28, 14, 76, 'Hot & rainy, hurricane season', 'Rain gear, light clothes, check weather'],
    [29, 13, 74, 'Very hot & humid', 'Light clothing, stay hydrated'],
    [29, 15, 76, 'Hot, peak hurricane season', 'Rain gear, monitor weather'],
    [28, 16, 78, 'Hot & rainy', 'Rain gear, light breathable clothes'],
    [27, 12, 74, 'Warm, late hurricane season', 'Light clothes, rain jacket'],
    [24, 7, 70, 'Warm & pleasant', 'Light clothing, light layers'],
    [22, 5, 70, 'Warm & pleasant', 'Light clothing, light jacket for AC'],
  ],
  MEX: [
    [14, 3, 44, 'Cool & dry', 'Warm layers for morning/evening, sunscreen'],
    [16, 2, 40, 'Cool & dry', 'Layers, sunscreen'],
    [18, 3, 36, 'Warm & dry', 'Light clothing, sunscreen, layers for evening'],
    [19, 5, 38, 'Warm & dry', 'Light clothing, sunscreen'],
    [19, 10, 46, 'Warm, rains start', 'Light clothing, rain jacket'],
    [18, 16, 56, 'Warm & rainy', 'Rain gear, layers for evening'],
    [17, 20, 58, 'Cool & rainy', 'Rain gear, warm layers for evening'],
    [17, 19, 58, 'Cool & rainy', 'Rain jacket, layers'],
    [17, 18, 60, 'Cool & rainy', 'Rain gear, warm layers'],
    [16, 9, 52, 'Cool, rains ending', 'Layers, light rain jacket'],
    [15, 4, 46, 'Cool & dry', 'Warm layers for morning/evening'],
    [14, 3, 46, 'Cool & dry', 'Warm layers, jacket'],
  ],
  BOG: [
    [14, 6, 76, 'Cool & mild, some rain', 'Warm layers, rain jacket'],
    [14, 7, 74, 'Cool, some rain', 'Warm layers, umbrella'],
    [14, 10, 76, 'Cool & rainy', 'Rain gear, warm layers'],
    [14, 14, 78, 'Cool & very rainy', 'Waterproof jacket, warm layers'],
    [14, 14, 78, 'Cool & rainy', 'Rain gear, warm layers'],
    [14, 8, 74, 'Cool, drier', 'Warm layers, light rain jacket'],
    [13, 6, 72, 'Cool & drier', 'Warm layers'],
    [14, 7, 72, 'Cool, some rain', 'Warm layers, rain jacket'],
    [14, 9, 74, 'Cool & rainy', 'Rain gear, warm layers'],
    [14, 14, 78, 'Cool & very rainy', 'Waterproof jacket, warm layers'],
    [14, 12, 78, 'Cool & rainy', 'Rain gear, warm layers'],
    [14, 8, 76, 'Cool, some rain', 'Warm layers, rain jacket'],
  ],
  LIM: [
    [23, 0, 78, 'Warm & humid, garua fog', 'Light clothing, light jacket for fog'],
    [24, 0, 76, 'Warm & humid', 'Light clothing'],
    [23, 0, 76, 'Warm & humid', 'Light clothing'],
    [21, 0, 78, 'Mild & overcast', 'Light layers'],
    [19, 0, 82, 'Cool & overcast', 'Light layers, light jacket'],
    [18, 1, 82, 'Cool & damp', 'Warm layers, jacket'],
    [17, 1, 84, 'Cool & damp, winter', 'Warm layers, jacket'],
    [16, 1, 84, 'Coolest month, overcast', 'Warm layers, jacket'],
    [17, 0, 82, 'Cool & overcast', 'Warm layers'],
    [18, 0, 80, 'Mild, warming up', 'Light layers'],
    [20, 0, 78, 'Mild & pleasant', 'Light layers'],
    [22, 0, 76, 'Warm & pleasant', 'Light clothing'],
  ],
  EZE: [
    [25, 8, 62, 'Hot & humid', 'Light clothing, rain jacket'],
    [24, 7, 64, 'Hot & humid', 'Light clothing, sunscreen'],
    [22, 8, 68, 'Warm & pleasant', 'Light layers'],
    [18, 7, 72, 'Mild & pleasant, autumn', 'Light jacket, layers'],
    [14, 6, 74, 'Cool, autumn', 'Warm jacket, layers'],
    [11, 6, 76, 'Cool, winter approaching', 'Warm coat, layers'],
    [10, 6, 76, 'Cool, winter', 'Warm coat, layers'],
    [12, 6, 72, 'Cool, late winter', 'Warm coat, layers'],
    [15, 6, 68, 'Mild, spring starting', 'Light jacket, layers'],
    [18, 8, 68, 'Mild & pleasant', 'Light layers, rain jacket'],
    [21, 7, 64, 'Warm & pleasant', 'Light clothing'],
    [24, 7, 62, 'Hot & humid', 'Light clothing, sunscreen'],
  ],
  GRU: [
    [23, 15, 78, 'Hot & rainy', 'Rain gear, light breathable clothes'],
    [24, 13, 76, 'Hot & rainy', 'Rain jacket, light clothes'],
    [23, 11, 76, 'Warm & rainy', 'Light layers, rain jacket'],
    [21, 6, 74, 'Mild & drier', 'Light layers'],
    [19, 5, 74, 'Mild & dry', 'Light layers, jacket'],
    [17, 4, 72, 'Cool & dry, winter', 'Warm layers, jacket'],
    [17, 3, 70, 'Cool & dry', 'Warm layers, jacket'],
    [18, 3, 66, 'Cool & dry', 'Warm layers'],
    [19, 6, 70, 'Mild, warming up', 'Light layers, rain jacket'],
    [20, 9, 74, 'Warm, rains returning', 'Light layers, rain gear'],
    [22, 11, 76, 'Warm & rainy', 'Light clothes, rain jacket'],
    [23, 14, 78, 'Hot & rainy', 'Rain gear, light breathable clothes'],
  ],
  SCL: [
    [21, 0, 48, 'Hot & dry', 'Light clothing, sunscreen'],
    [20, 0, 50, 'Hot & dry', 'Light clothing, sun protection'],
    [18, 1, 54, 'Warm & dry', 'Light layers'],
    [14, 2, 60, 'Mild, autumn', 'Light jacket, layers'],
    [11, 4, 68, 'Cool & rainy', 'Warm jacket, rain gear'],
    [8, 5, 74, 'Cool & rainy, winter', 'Warm coat, rain gear'],
    [8, 4, 74, 'Cool & rainy, winter', 'Warm coat, waterproof jacket'],
    [9, 3, 70, 'Cool, late winter', 'Warm coat, layers'],
    [12, 2, 64, 'Mild, spring starting', 'Light jacket, layers'],
    [15, 2, 58, 'Warm & pleasant', 'Light layers'],
    [18, 1, 52, 'Warm & dry', 'Light clothing, layers'],
    [20, 0, 48, 'Hot & dry', 'Light clothing, sunscreen'],
  ],
  PTY: [
    [27, 5, 72, 'Warm & mostly dry', 'Light clothing, sunscreen'],
    [27, 3, 70, 'Warm & dry', 'Light clothing, sun hat'],
    [28, 3, 68, 'Hot & dry', 'Light clothing, sun protection'],
    [28, 7, 72, 'Hot, rains starting', 'Light clothes, rain jacket'],
    [27, 18, 80, 'Rainy season', 'Rain gear, light clothes'],
    [27, 16, 80, 'Rainy season', 'Umbrella, waterproof bag'],
    [27, 14, 78, 'Rainy season', 'Rain gear, light clothes'],
    [27, 16, 80, 'Rainy season', 'Rain gear, quick-dry clothes'],
    [27, 16, 82, 'Rainy season', 'Waterproof gear, umbrella'],
    [27, 20, 82, 'Wettest month', 'Full rain gear, waterproof everything'],
    [27, 18, 82, 'Very rainy', 'Rain gear, waterproof bag'],
    [27, 10, 76, 'Drying out', 'Light clothing, rain jacket'],
  ],
  SJO: [
    [21, 1, 68, 'Warm & dry', 'Light layers, sunscreen'],
    [21, 1, 64, 'Warm & dry', 'Light clothing'],
    [22, 2, 62, 'Warm & dry', 'Light clothing, sunscreen'],
    [22, 6, 68, 'Warm, rains start', 'Light clothes, rain jacket'],
    [22, 16, 78, 'Rainy season (green season)', 'Rain gear, light clothes'],
    [21, 17, 80, 'Rainy season', 'Rain gear, waterproof bag'],
    [21, 14, 78, 'Rainy season', 'Rain jacket, light clothes'],
    [21, 17, 80, 'Rainy season', 'Rain gear, quick-dry clothes'],
    [21, 19, 82, 'Wettest month', 'Full rain gear, waterproof everything'],
    [21, 18, 82, 'Very rainy', 'Rain gear, waterproof bag'],
    [21, 9, 76, 'Rains easing', 'Light rain jacket, layers'],
    [21, 3, 70, 'Dry season starting', 'Light clothing, light layers'],
  ],
  CUN: [
    [24, 4, 76, 'Warm & pleasant', 'Light clothing, beach wear'],
    [24, 3, 74, 'Warm & dry', 'Beach wear, sunscreen'],
    [26, 2, 72, 'Warm & dry', 'Light clothing, sun protection'],
    [27, 2, 72, 'Hot & dry', 'Light clothing, sunscreen'],
    [28, 6, 74, 'Hot, rains start', 'Light clothes, rain jacket'],
    [28, 12, 78, 'Hot & rainy, hurricane season', 'Rain gear, check weather alerts'],
    [29, 10, 76, 'Hot & humid', 'Light clothes, rain jacket'],
    [29, 11, 78, 'Hot, peak hurricane season', 'Rain gear, monitor storms'],
    [28, 14, 80, 'Hot & rainy', 'Rain gear, light clothes'],
    [27, 12, 78, 'Warm, late hurricane season', 'Rain jacket, light clothes'],
    [26, 6, 76, 'Warm & pleasant', 'Light clothing, beach wear'],
    [24, 4, 76, 'Warm & pleasant', 'Beach wear, light layers for evening'],
  ],

  // ========== AFRICA ==========
  RAK: [
    [12, 4, 68, 'Cool & pleasant', 'Warm layers, jacket for evening'],
    [14, 4, 62, 'Mild & pleasant', 'Light layers'],
    [17, 4, 56, 'Warm & pleasant', 'Light clothing, layers'],
    [19, 4, 50, 'Warm & dry', 'Light clothing, sunscreen'],
    [23, 2, 42, 'Hot & dry', 'Light clothing, sun hat'],
    [28, 0, 34, 'Very hot & dry', 'Light clothing, stay hydrated'],
    [32, 0, 28, 'Extreme heat', 'Light loose clothes, avoid midday sun'],
    [32, 0, 30, 'Very hot', 'Light clothing, stay in shade midday'],
    [27, 1, 42, 'Hot & dry', 'Light clothing, sunscreen'],
    [22, 3, 52, 'Warm & pleasant', 'Light layers'],
    [17, 4, 62, 'Mild & pleasant', 'Light jacket, layers'],
    [13, 4, 68, 'Cool & pleasant', 'Warm layers, jacket'],
  ],
  CPT: [
    [22, 2, 58, 'Hot & dry, peak summer', 'Light clothing, sunscreen, hat'],
    [22, 1, 58, 'Hot & dry', 'Beach wear, sun protection'],
    [21, 2, 62, 'Warm & dry', 'Light clothing, layers for evening'],
    [18, 4, 68, 'Mild, autumn', 'Light jacket, layers'],
    [15, 7, 76, 'Cool & rainy', 'Warm jacket, rain gear'],
    [13, 8, 78, 'Cool & wet, winter', 'Warm coat, waterproof jacket'],
    [12, 9, 80, 'Cold & wet, winter', 'Warm coat, rain gear'],
    [13, 8, 78, 'Cool & wet', 'Warm coat, waterproof layers'],
    [14, 5, 74, 'Cool, spring starting', 'Warm jacket, layers'],
    [17, 4, 68, 'Mild & pleasant', 'Light layers'],
    [19, 2, 62, 'Warm & dry', 'Light clothing, sunscreen'],
    [21, 2, 58, 'Hot & dry', 'Light clothing, beach essentials'],
  ],
  NBO: [
    [19, 4, 62, 'Warm & dry', 'Light layers, sunscreen'],
    [20, 4, 58, 'Warm & dry', 'Light clothing, sun hat'],
    [20, 7, 62, 'Warm, short rains', 'Light layers, rain jacket'],
    [19, 14, 72, 'Long rains season', 'Rain gear, warm layers'],
    [18, 12, 72, 'Cool & rainy', 'Rain gear, warm layers'],
    [17, 4, 64, 'Cool & dry', 'Warm layers, jacket'],
    [16, 3, 62, 'Coolest month', 'Warm layers, jacket'],
    [17, 4, 60, 'Cool & dry', 'Warm layers'],
    [18, 4, 58, 'Warm & dry', 'Light layers'],
    [19, 8, 66, 'Warm, short rains', 'Rain jacket, light layers'],
    [18, 12, 72, 'Short rains season', 'Rain gear, warm layers'],
    [18, 7, 66, 'Warm, rains easing', 'Light layers, rain jacket'],
  ],
  JNB: [
    [21, 13, 64, 'Warm & rainy, summer', 'Rain gear, light clothes, sunscreen'],
    [20, 10, 66, 'Warm & rainy', 'Rain jacket, light clothes'],
    [19, 8, 64, 'Mild, rains easing', 'Light layers, rain jacket'],
    [16, 4, 58, 'Mild & dry, autumn', 'Light jacket, layers'],
    [13, 2, 48, 'Cool & dry', 'Warm jacket, layers'],
    [10, 1, 44, 'Cold & dry, winter', 'Warm coat, layers'],
    [10, 1, 42, 'Cold & dry', 'Warm coat, hat, layers'],
    [13, 1, 38, 'Cool & dry', 'Warm layers, jacket'],
    [16, 2, 40, 'Warm & dry, spring', 'Light layers'],
    [18, 7, 52, 'Warm, rains returning', 'Light layers, rain jacket'],
    [19, 11, 60, 'Warm & rainy', 'Rain gear, light clothes'],
    [20, 12, 64, 'Warm & rainy', 'Rain gear, light clothes, sunscreen'],
  ],
  DSS: [
    [21, 0, 62, 'Warm & dry', 'Light layers'],
    [21, 0, 60, 'Warm & dry', 'Light clothing'],
    [22, 0, 58, 'Warm & dry', 'Light clothing, sunscreen'],
    [22, 0, 58, 'Hot & dry', 'Light clothing, sun hat'],
    [24, 0, 62, 'Hot & dry', 'Light clothing, stay hydrated'],
    [27, 2, 72, 'Hot & humid, rains start', 'Light clothes, rain jacket'],
    [27, 10, 80, 'Rainy season', 'Rain gear, light clothes'],
    [27, 16, 84, 'Peak rainy season', 'Full rain gear, waterproof bag'],
    [27, 14, 84, 'Rainy season', 'Rain gear, light clothes'],
    [27, 6, 78, 'Warm, rains easing', 'Light clothes, rain jacket'],
    [25, 1, 68, 'Warm & dry', 'Light clothing'],
    [22, 0, 64, 'Warm & dry, pleasant', 'Light layers'],
  ],

  // ========== CAUCASUS ==========
  TBS: [
    [2, 4, 72, 'Cold, possible snow', 'Warm coat, layers'],
    [4, 4, 68, 'Cold, some rain/snow', 'Warm coat, layers'],
    [8, 5, 62, 'Cool, spring starting', 'Warm jacket, layers'],
    [14, 7, 58, 'Mild & pleasant', 'Light jacket, layers'],
    [18, 9, 62, 'Warm & pleasant', 'Light layers, rain jacket'],
    [23, 6, 56, 'Hot & dry', 'Light clothing, sunscreen'],
    [26, 4, 50, 'Very hot', 'Light clothes, sun hat, stay hydrated'],
    [26, 4, 48, 'Very hot', 'Light clothing, sunscreen'],
    [22, 4, 54, 'Warm & pleasant', 'Light layers'],
    [16, 5, 64, 'Cool & pleasant', 'Light jacket, layers'],
    [9, 5, 70, 'Cool to cold', 'Warm jacket, layers'],
    [3, 4, 74, 'Cold, possible snow', 'Warm coat, layers'],
  ],
  BUS: [
    [7, 10, 76, 'Cool & rainy', 'Warm coat, waterproof jacket'],
    [7, 9, 76, 'Cool & rainy', 'Warm coat, umbrella'],
    [9, 9, 74, 'Cool, spring starting', 'Warm jacket, rain gear'],
    [13, 7, 72, 'Mild & pleasant', 'Light jacket, layers'],
    [17, 7, 74, 'Warm & pleasant', 'Light layers, rain jacket'],
    [22, 7, 72, 'Warm & pleasant', 'Light clothing, beach wear, rain jacket'],
    [24, 5, 72, 'Hot & humid', 'Beach wear, sunscreen'],
    [25, 5, 72, 'Hot & humid', 'Light clothing, beach essentials'],
    [22, 7, 72, 'Warm & pleasant', 'Light layers, rain jacket'],
    [18, 9, 74, 'Mild & rainy', 'Warm jacket, rain gear'],
    [13, 9, 76, 'Cool & rainy', 'Warm jacket, waterproof coat'],
    [9, 10, 76, 'Cool & wet', 'Warm coat, rain gear'],
  ],

  // ========== OCEANIA ==========
  SYD: [
    [23, 8, 68, 'Warm & pleasant, summer', 'Beach wear, sunscreen'],
    [23, 9, 70, 'Warm & humid', 'Light clothing, rain jacket'],
    [22, 9, 68, 'Warm, autumn starting', 'Light layers'],
    [19, 8, 66, 'Mild & pleasant', 'Light jacket, layers'],
    [16, 8, 66, 'Cool & pleasant', 'Warm jacket, layers'],
    [14, 8, 68, 'Cool, winter', 'Warm jacket, layers'],
    [13, 6, 64, 'Cool & dry, winter', 'Warm coat, layers'],
    [14, 5, 60, 'Cool & dry', 'Warm layers, jacket'],
    [17, 6, 60, 'Mild, spring starting', 'Light jacket, layers'],
    [19, 7, 62, 'Mild & pleasant', 'Light layers'],
    [20, 8, 64, 'Warm & pleasant', 'Light clothing, rain jacket'],
    [22, 8, 66, 'Warm, summer starting', 'Beach wear, sunscreen'],
  ],
  AKL: [
    [20, 7, 72, 'Warm & pleasant, summer', 'Light clothing, sunscreen'],
    [20, 7, 74, 'Warm & humid', 'Light clothing, rain jacket'],
    [19, 7, 72, 'Warm, autumn starting', 'Light layers'],
    [16, 9, 76, 'Mild & rainy', 'Light jacket, rain gear'],
    [14, 10, 78, 'Cool & wet', 'Warm jacket, waterproof coat'],
    [12, 11, 80, 'Cool & wet, winter', 'Warm coat, rain gear'],
    [11, 12, 80, 'Cold & wet, winter', 'Warm coat, waterproof jacket'],
    [12, 11, 78, 'Cool & wet', 'Warm coat, layers, umbrella'],
    [13, 9, 76, 'Cool, spring starting', 'Warm jacket, layers'],
    [15, 9, 74, 'Mild & rainy', 'Light jacket, rain gear'],
    [17, 8, 72, 'Mild & pleasant', 'Light layers, rain jacket'],
    [19, 7, 72, 'Warm & pleasant', 'Light clothing, sunscreen'],
  ],
}

/**
 * Get climate data for a destination by IATA code and month number (1-12).
 */
export function getClimateData(cityCode: string, month: number): ClimateData | null {
  const code = cityCode.toUpperCase()
  const data = climateDb[code]
  if (!data) return null

  const monthIndex = month - 1
  if (monthIndex < 0 || monthIndex > 11) return null

  return toClimate(fromCompact(data)[monthIndex])
}
