'use client'

import { useState, useRef } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { trackHotelClick } from '@/lib/track-client'

interface DailyActivity {
  time: string
  activity: string
  estimated_cost: number
}

interface DailyItineraryDay {
  day: number
  activities: DailyActivity[]
  total_day_cost: number
}

interface HotelRec {
  name: string
  estimated_price_per_night: number
  neighborhood?: string
  why_recommended?: string
  link?: string
  rating?: number
  reviews?: number
  type?: string
  is_real_data?: boolean
}

interface ItineraryDetailProps {
  destination: string
  country: string
  tripDuration: number
  departDate: string
  returnDate: string
  // AI-generated content
  whyThisPlace?: string
  bestTimeToGo?: string
  daily_itinerary?: DailyItineraryDay[]
  itinerary?: { day: number; activities: string[] }[]
  hotel_recommendations?: HotelRec[]
  local_transportation?: { airport_to_city: string; daily_transport: string; estimated_daily_cost: number }
  best_local_food?: string[]
  insider_tip?: string
  localTip?: string
  // Formatting
  fmt: (amount: number) => string
  detailsLoading?: boolean
}

function formatDate(dateStr: string): string {
  if (!dateStr) return ''
  try {
    return new Date(dateStr + 'T00:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
  } catch { return dateStr }
}

export default function ItineraryDetail({
  destination, country, tripDuration, departDate, returnDate,
  whyThisPlace, bestTimeToGo, daily_itinerary, itinerary,
  hotel_recommendations, local_transportation, best_local_food,
  insider_tip, localTip, fmt, detailsLoading,
}: ItineraryDetailProps) {
  const [open, setOpen] = useState(false)
  const [fullscreen, setFullscreen] = useState(false)
  const printRef = useRef<HTMLDivElement>(null)

  const hasContent = !!(whyThisPlace || daily_itinerary?.length || itinerary?.length || best_local_food?.length || hotel_recommendations?.length)

  const handleDownloadPDF = async () => {
    if (!printRef.current) return

    // Use browser print as PDF (most reliable cross-browser approach)
    const content = printRef.current.innerHTML
    const printWindow = window.open('', '_blank', 'width=800,height=600')
    if (!printWindow) return

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${destination} Itinerary — GlobePilots</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1e293b; padding: 32px; max-width: 800px; margin: 0 auto; }
          h1 { font-size: 28px; margin-bottom: 4px; }
          h2 { font-size: 20px; margin-top: 24px; margin-bottom: 8px; color: #0ea5e9; }
          h3 { font-size: 16px; margin-top: 16px; margin-bottom: 6px; }
          p { font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 8px; }
          .meta { color: #64748b; font-size: 13px; margin-bottom: 20px; }
          .day-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 12px; }
          .activity { display: flex; justify-content: space-between; padding: 4px 0; font-size: 13px; }
          .activity-time { color: #0ea5e9; font-weight: 600; min-width: 80px; }
          .activity-cost { color: #64748b; font-weight: 600; }
          .food-list { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; }
          .food-tag { background: #fef3c7; color: #92400e; padding: 4px 12px; border-radius: 20px; font-size: 12px; }
          .hotel { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px; padding: 12px; margin-bottom: 8px; }
          .tip { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 12px 16px; border-radius: 0 8px 8px 0; margin-top: 16px; }
          .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
          @media print { body { padding: 16px; } }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">Generated by GlobePilots.com — AI-powered travel planning</div>
      </body>
      </html>
    `)
    printWindow.document.close()
    // Small delay to let styles render
    setTimeout(() => {
      printWindow.print()
      printWindow.close()
    }, 300)
  }

  return (
    <>
      {/* Trigger button */}
      <button
        onClick={() => setOpen(true)}
        disabled={!hasContent && !detailsLoading}
        className={`w-full py-4 px-6 rounded-xl font-semibold text-center transition-all ${
          hasContent
            ? 'bg-gradient-to-r from-sky-500 to-cyan-400 text-white shadow-lg shadow-sky-500/25 hover:shadow-sky-500/40 hover:scale-[1.01]'
            : detailsLoading
              ? 'bg-white/[0.06] text-white/50 border border-white/10 animate-pulse'
              : 'bg-white/[0.04] text-white/30 border border-white/[0.06] cursor-not-allowed'
        }`}
        aria-label="View full itinerary details"
      >
        {detailsLoading ? (
          <span className="flex items-center justify-center gap-2">
            <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            Building your itinerary...
          </span>
        ) : hasContent ? (
          <span>View Full Itinerary &amp; Details</span>
        ) : (
          <span>No itinerary available</span>
        )}
      </button>

      {/* Detail popup */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[90] flex items-center justify-center"
          >
            {/* Backdrop */}
            <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={() => setOpen(false)} />

            {/* Panel */}
            <motion.div
              initial={{ y: 30, opacity: 0, scale: 0.97 }}
              animate={{ y: 0, opacity: 1, scale: 1 }}
              exit={{ y: 30, opacity: 0, scale: 0.97 }}
              transition={{ type: 'spring', stiffness: 400, damping: 30 }}
              className={`relative w-full bg-slate-900 shadow-2xl border border-white/10 overflow-hidden ${
                fullscreen
                  ? 'max-w-none max-h-none h-screen rounded-none'
                  : 'max-w-4xl max-h-[92vh] rounded-2xl mx-4'
              }`}
            >
              {/* Header */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-white/[0.06] bg-white/[0.02]">
                <div>
                  <h2 className="text-xl font-bold text-white">{destination} Itinerary</h2>
                  <p className="text-sm text-white/50">{formatDate(departDate)} — {formatDate(returnDate)} · {tripDuration} nights</p>
                </div>
                <div className="flex items-center gap-2">
                  {hasContent && (
                    <button
                      onClick={handleDownloadPDF}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium text-sky-400 hover:bg-sky-500/10 transition"
                      aria-label="Download itinerary as PDF"
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                      PDF
                    </button>
                  )}
                  <button
                    onClick={() => setFullscreen(!fullscreen)}
                    className="w-8 h-8 items-center justify-center rounded-lg text-white/40 hover:text-white hover:bg-white/10 transition hidden sm:flex"
                    aria-label={fullscreen ? 'Exit fullscreen' : 'Fullscreen'}
                  >
                    {fullscreen ? (
                      <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M6 2v4H2M10 14v-4h4M2 10h4v4M14 6h-4V2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
                    ) : (
                      <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M2 6V2h4M14 10v4h-4M10 2h4v4M6 14H2v-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
                    )}
                  </button>
                  <button
                    onClick={() => setOpen(false)}
                    className="w-8 h-8 flex items-center justify-center rounded-lg text-white/40 hover:text-white hover:bg-white/10 transition"
                    aria-label="Close itinerary"
                  >
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
                  </button>
                </div>
              </div>

              {/* Scrollable content */}
              <div className="overflow-y-auto p-6 space-y-6" style={{ maxHeight: fullscreen ? 'calc(100vh - 72px)' : 'calc(92vh - 72px)' }}>

                {/* Hidden print-ready content for PDF */}
                <div ref={printRef} className="hidden">
                  <h1>{destination}, {country}</h1>
                  <p className="meta">{formatDate(departDate)} — {formatDate(returnDate)} · {tripDuration} nights</p>

                  {whyThisPlace && <><h2>Why {destination}?</h2><p>{whyThisPlace}</p></>}

                  {daily_itinerary && daily_itinerary.length > 0 && (
                    <>
                      <h2>Daily Itinerary</h2>
                      {daily_itinerary.map(day => (
                        <div key={day.day} className="day-card">
                          <h3>Day {day.day} — ${day.total_day_cost} total</h3>
                          {day.activities.map((a, i) => (
                            <div key={i} className="activity">
                              <span><span className="activity-time">{a.time}</span> {a.activity}</span>
                              <span className="activity-cost">${a.estimated_cost}</span>
                            </div>
                          ))}
                        </div>
                      ))}
                    </>
                  )}

                  {hotel_recommendations && hotel_recommendations.length > 0 && (
                    <>
                      <h2>Recommended Hotels</h2>
                      {hotel_recommendations.map((h, i) => (
                        <div key={i} className="hotel">
                          <strong>{h.name}</strong> — ${h.estimated_price_per_night}/night
                          {h.neighborhood && <span> · {h.neighborhood}</span>}
                          {h.why_recommended && <p>{h.why_recommended}</p>}
                        </div>
                      ))}
                    </>
                  )}

                  {best_local_food && best_local_food.length > 0 && (
                    <><h2>Must-Try Food</h2><div className="food-list">{best_local_food.map((f, i) => <span key={i} className="food-tag">{f}</span>)}</div></>
                  )}

                  {(insider_tip || localTip) && (
                    <div className="tip"><strong>Insider Tip:</strong> {insider_tip || localTip}</div>
                  )}

                  {local_transportation && (
                    <><h2>Getting Around</h2><p><strong>Airport to city:</strong> {local_transportation.airport_to_city}</p><p><strong>Daily transport:</strong> {local_transportation.daily_transport} (~${local_transportation.estimated_daily_cost}/day)</p></>
                  )}
                </div>

                {/* ── Visible popup content ── */}

                {/* Why This Destination */}
                {whyThisPlace && (
                  <div className="bg-white/[0.04] rounded-xl p-5 border border-white/10">
                    <h3 className="text-lg font-bold text-white mb-2">Why {destination}?</h3>
                    <p className="text-white/70 leading-relaxed">{whyThisPlace}</p>
                  </div>
                )}

                {/* Best Time to Go */}
                {bestTimeToGo && (
                  <div className="bg-sky-500/10 border border-sky-500/20 rounded-lg p-4">
                    <p className="text-sm text-white/80">
                      <span className="font-semibold text-sky-300">Best time to go:</span> {bestTimeToGo}
                    </p>
                  </div>
                )}

                {/* Daily Itinerary */}
                {daily_itinerary && daily_itinerary.length > 0 && (
                  <div>
                    <h3 className="text-lg font-bold text-white mb-1">Your Daily Itinerary</h3>
                    <p className="text-xs text-white/40 mb-4">AI-suggested activities — verify availability locally</p>
                    <div className="space-y-4">
                      {daily_itinerary.map(day => (
                        <div key={day.day} className="bg-white/[0.04] rounded-lg p-4 border border-white/10">
                          <div className="flex justify-between items-center mb-3">
                            <h4 className="font-semibold text-white">Day {day.day}</h4>
                            <span className="text-sm font-semibold text-emerald-400">${day.total_day_cost}/day</span>
                          </div>
                          <div className="space-y-2">
                            {day.activities.map((activity, idx) => (
                              <div key={idx} className="flex justify-between items-start">
                                <div className="flex-1">
                                  <p className="text-sm font-medium text-sky-300">{activity.time}</p>
                                  <p className="text-white/70">{activity.activity}</p>
                                </div>
                                <p className="text-sm font-semibold text-white/50 ml-4">${activity.estimated_cost}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Simple itinerary fallback */}
                {!daily_itinerary?.length && itinerary && itinerary.length > 0 && (
                  <div>
                    <h3 className="text-lg font-bold text-white mb-4">Your Itinerary</h3>
                    <div className="space-y-4">
                      {itinerary.map(day => (
                        <div key={day.day} className="bg-white/[0.04] rounded-lg p-4 border border-white/10">
                          <h4 className="font-semibold text-white mb-2">Day {day.day}</h4>
                          <ul className="space-y-1">
                            {day.activities.map((a, i) => (
                              <li key={i} className="text-white/70 flex items-start">
                                <span className="text-sky-400 mr-2">&bull;</span>{a}
                              </li>
                            ))}
                          </ul>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Hotels */}
                {hotel_recommendations && hotel_recommendations.length > 0 && (
                  <div>
                    <h3 className="text-lg font-bold text-white mb-3">
                      Where to Stay
                      {hotel_recommendations[0]?.is_real_data && (
                        <span className="ml-2 text-xs font-normal text-emerald-400/70">Live prices</span>
                      )}
                    </h3>
                    <div className="space-y-3">
                      {hotel_recommendations.map((hotel, idx) => (
                        <a
                          key={idx}
                          href={`https://www.booking.com/searchresults.html?ss=${encodeURIComponent(hotel.name + ', ' + destination + ', ' + country)}${departDate ? `&checkin=${departDate}` : ''}${returnDate ? `&checkout=${returnDate}` : ''}&group_adults=1&no_rooms=1`}
                          target="_blank"
                          rel="noopener noreferrer"
                          onClick={() => trackHotelClick({ hotel: hotel.name, destination, pricePerNight: hotel.estimated_price_per_night })}
                          className="block bg-white/[0.04] rounded-lg p-4 border border-white/10 hover:bg-white/[0.08] transition group"
                          aria-label={`View ${hotel.name} on Booking.com`}
                        >
                          <div className="flex justify-between items-start mb-1">
                            <h4 className="font-semibold text-white group-hover:text-sky-400 transition">{hotel.name}</h4>
                            <p className="text-emerald-400 font-bold whitespace-nowrap ml-4">{fmt(hotel.estimated_price_per_night)}/night</p>
                          </div>
                          {hotel.rating && hotel.rating > 0 && (
                            <p className="text-xs text-amber-400/80 mb-1">{hotel.rating}/5{hotel.reviews ? ` (${hotel.reviews.toLocaleString()} reviews)` : ''}</p>
                          )}
                          {hotel.neighborhood && <p className="text-sm text-white/50">{hotel.neighborhood}</p>}
                          {hotel.why_recommended && <p className="text-sm text-white/70 mt-1">{hotel.why_recommended}</p>}
                        </a>
                      ))}
                    </div>
                  </div>
                )}

                {/* Transport */}
                {local_transportation && (
                  <div className="bg-sky-500/10 border border-sky-500/20 rounded-lg p-4">
                    <h3 className="text-lg font-bold text-white mb-3">Getting Around</h3>
                    <div className="space-y-2 text-sm">
                      <p className="text-white/80"><span className="text-sky-300 font-medium">Airport to city:</span> {local_transportation.airport_to_city}</p>
                      <p className="text-white/80"><span className="text-sky-300 font-medium">Daily transport:</span> {local_transportation.daily_transport}</p>
                      <p className="text-white/60">Estimated: {fmt(local_transportation.estimated_daily_cost)}/day</p>
                    </div>
                  </div>
                )}

                {/* Food */}
                {best_local_food && best_local_food.length > 0 && (
                  <div>
                    <h3 className="text-lg font-bold text-white mb-3">Must-Try Local Food</h3>
                    <div className="flex flex-wrap gap-2">
                      {best_local_food.map((food, idx) => (
                        <span key={idx} className="bg-amber-500/10 border border-amber-500/20 text-amber-300 px-4 py-2 rounded-full text-sm font-medium">{food}</span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Insider Tip */}
                {(insider_tip || localTip) && (
                  <div className="bg-amber-500/10 border-l-4 border-amber-500/40 p-4 rounded-r-lg">
                    <h3 className="font-semibold text-white mb-1">Insider Tip</h3>
                    <p className="text-white/70">{insider_tip || localTip}</p>
                  </div>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}
